// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXxcLYtyxGp26qee5ZVj0P1cp4WpJTZZE',
    appId: '1:289301897499:web:146e884d56c8e8dad4f3be',
    messagingSenderId: '289301897499',
    projectId: 'gfi-project-7bbd2',
    authDomain: 'gfi-project-7bbd2.firebaseapp.com',
    storageBucket: 'gfi-project-7bbd2.appspot.com',
    measurementId: 'G-QQ2C2EFM9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsdrCodO-Z4LS2eXFtZwV_lmXPZH82xqI',
    appId: '1:289301897499:android:ad3549218ad45e2dd4f3be',
    messagingSenderId: '289301897499',
    projectId: 'gfi-project-7bbd2',
    storageBucket: 'gfi-project-7bbd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtUY9nhzMH4QFF_a5pL7oTaSW9-d28BPg',
    appId: '1:289301897499:ios:e7f51e519525c4f0d4f3be',
    messagingSenderId: '289301897499',
    projectId: 'gfi-project-7bbd2',
    storageBucket: 'gfi-project-7bbd2.appspot.com',
    iosBundleId: 'tdtu.edu.vn.gfi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtUY9nhzMH4QFF_a5pL7oTaSW9-d28BPg',
    appId: '1:289301897499:ios:e7f51e519525c4f0d4f3be',
    messagingSenderId: '289301897499',
    projectId: 'gfi-project-7bbd2',
    storageBucket: 'gfi-project-7bbd2.appspot.com',
    iosBundleId: 'tdtu.edu.vn.gfi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXxcLYtyxGp26qee5ZVj0P1cp4WpJTZZE',
    appId: '1:289301897499:web:78166acb57c565a1d4f3be',
    messagingSenderId: '289301897499',
    projectId: 'gfi-project-7bbd2',
    authDomain: 'gfi-project-7bbd2.firebaseapp.com',
    storageBucket: 'gfi-project-7bbd2.appspot.com',
    measurementId: 'G-2KE7Q5B3LW',
  );
}
